version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large
    steps:
      - run: sudo apt-get update && sudo apt-get install -y debhelper cmake python3-distutils ninja-build clang lld devscripts
      - checkout:
          path: cheerp-compiler
      - run:
          name: build-cheerp-compiler
          working_directory: ~/project/cheerp-compiler
          command: |
            export NINJA_STATUS="[%u/%r/%f] "
            dch -b -v 0-latest-1 "Internal build" -m
            dpkg-buildpackage -b
            mkdir tmp
            dpkg -x ../cheerp-llvm-clang_*.deb tmp
            sudo mkdir /opt/cheerp/
            sudo cp -rv tmp/opt/cheerp/* /opt/cheerp
            rm -rf tmp
      - store_artifacts:
          path: ~/project/cheerp-llvm-clang_*.deb
          destination: cheerp-compiler-artifact
  test_trigger:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium
    steps:
      - run:
          name: trigger-conditional-job
          command: echo "triggering conditional job"
  conditional_job:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium
    steps:
      - run: echo "I've ran!"
      - run: exit 0

parameters:
  run_conditional_job:
    type: boolean
    default: false

workflows:
  cheerp-compiler-monorepo:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circle-ci
  trigger-pipeline:
    jobs:
      - test_trigger:
          filters:
            branches:
              only:
                - circle-ci
  conditional_wf:
    when: << pipeline.parameters.run_conditional_job >>
    jobs:
      - conditional_job
