version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large
    steps:
      - run: sudo apt-get update && sudo apt-get install -y debhelper cmake python3-distutils nodejs ninja-build clang lld
      - checkout:
          path: cheerp-compiler
      - run:
          name: build-cheerp-compiler
          working_directory: ~/project/cheerp-compiler
          command: |
            dpkg-buildpackage -b
            mkdir tmp
            dpkg -x ../cheerp-llvm-clang_*.deb tmp
            sudo mkdir /opt/cheerp/
            sudo cp -rv tmp/opt/cheerp/* /opt/cheerp
            rm -rf tmp

workflows:
  cheerp-compiler-monorepo:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circle-ci
