version: 2.1

aliases:
  - &ubuntu
    image: ubuntu-2004:202111-02

jobs:
  build-cheerp-compiler:
    machine: *ubuntu
    resource_class: large
    environment:
      - NINJA_STATUS: "[%u/%r/%f] "
    steps:
      - run: sudo apt-get update && sudo apt-get install -y debhelper cmake ninja-build clang lld devscripts
      - run:
          name: Checkout
          command: |
            git clone --depth=1 --no-single-branch https://github.com/leaningtech/cheerp-compiler cheerp-compiler
            cd cheerp-compiler
            git checkout << pipeline.parameters.cheerp-compiler-branch >>
      - run:
          name: Set up environment
          working_directory: ~/project/cheerp-compiler
          command: |
            if [ << pipeline.parameters.tag >> != master ]; then
              git checkout << pipeline.parameters.tag >>
              echo "export VERSION_NO=`echo << pipeline.parameters.tag >> | cut --complement -c1-7`" >> $BASH_ENV
            else
              git checkout << pipeline.parameters.cheerp-compiler-branch >>
              echo "export VERSION_NO='0-latest'" >> $BASH_ENV
            fi
      - run:
          name: Build cheerp compiler
          working_directory: ~/project/cheerp-compiler
          command: |
            dch -b -v 0-latest-1 "Internal build" -m
            dpkg-buildpackage -b -d

parameters:
  tag:
    type: string
    default: "master"
  cheerp-compiler-branch:
    type: string
    default: << pipeline.git.branch >>
  cheerp-utils-branch:
    type: string
    default: "master"
  cheerp-newlib-branch:
    type: string
    default: "master"
  cheerp-libs-branch:
    type: string
    default: "master"

workflows:
  build-cheerp-compiler:
    jobs:
      - build-cheerp-compiler
